### ISSUE TITLE
Embbed JSON file in a MOD

### ISSUE THREAD

**Issue by Noxalus** [Hello-Meow/ModTool#11]
Hello,

I would like to be able to include JSON files in my MOD and allow the base project read them, is there a way to do that?

From what I found, even if JSON files are present in the MOD project, they don't seem to be imported in the MOD export (not even in the asset bundle?).

How would you do that?

Thanks in advance for your answer!

**Comment by Hello-Meow** [comment]
Hi,

TextAssets are currently not included, but it sounds like a useful thing to have. I'll look into including them.

Instead of a JSON file, you could include ScriptableObject assets.

**Comment by Noxalus** [comment]
It would be great yes! 👍  

For ScriptableObject too, but I will still need to be able to read JSON files in my case.

**Comment by egk696** [comment]
Yes 👍 support for TextAssets would be greatly appreciated !

**Comment by Noxalus** [comment]
I was wondering, is it possible to use Addressable assets from a MOD exported by ModTool in a project?

Wouldn't be the best way to easily use content from a MOD?
