### ISSUE TITLE
How to use ModTools namespace in my project scripts?

### ISSUE THREAD

**Issue by Noxalus** [Hello-Meow/ModTool#12]
Hello,

In my project, I have a script that will get all loaded mods and get  the prefab with a specific name from a specified mod, something like that:

```
Mod mod = ModManager.instance.mods.First(m => m.name == modName);
_prefabResource = mod.GetAsset<GameObject>(prefabName).GetComponent<Entity>();
```

But to use `Mod` type, I need to use `ModTools` namespace and from the moment I use it in my project assembly, when I export the Unity package for modding, I get this error:

```
Unable to resolve reference 'ModTool'. Is the assembly missing or incompatible with the current platform?
```

Adding `ModTool` to the list of API assemblies in the ModTool's settings doesn't seem the right thing to do (and it doesn't work anyway). 

So how are we supposed to use the ModTool in the project scripts?

Thanks in advance for your help!

**Comment by Hello-Meow** [comment]
Hi,

Does it give any other errors or warnings?

**Comment by Noxalus** [comment]
There is another error before, but it's linked to the one I posted:

```
Assembly 'Library/ScriptAssemblies/Assembly-CSharp.dll' will not be loaded due to errors:
Reference has errors 'Game'.
```

The complete error after is this:

```
Assembly 'Assets/ModTool/Game.dll' will not be loaded due to errors:
Unable to resolve reference 'ModTool'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```

Do you confirm that I shouldn't add `ModTool` in the API assemblies list?

**Comment by Hello-Meow** [comment]
ModTool should not be added to the API assemblies.

I'm not sure what's going on here. Do all the assemblies target the same scripting runtime?

**Comment by Noxalus** [comment]
I think so because when I comment the 2 lines in my first post (in addition with the `using namespace ModTool`), it works as expected.

Without commenting these lines, my Game.dll depends on the ModTool.dll to work as expected since it's a dependency. But ModTool.dll is not included when I use the MOD exporter (only the DLL I've listed in the API assemblies list are).

Actually, I've just made a test copying the ModTool.dll from my game project to the MOD project, and it seems to work without any error anymore.

Isn't should be included by default by the exporter? 🤔

**Comment by Hello-Meow** [comment]
API assemblies shouldn't reference ModTool. They should only reference ModTool.Interface. Maybe that's what causing the issue.

**Comment by Noxalus** [comment]
Ok, but how can I get a prefab from a specific MOD using ModTool.Interface? 

The 2 lines I've used in my original post need Modtool and can't be called using ModTool.Interface:

```
Mod mod = ModManager.instance.mods.First(m => m.name == modName);
_prefabResource = mod.GetAsset<GameObject>(prefabName).GetComponent<Entity>();
```

**Comment by Hello-Meow** [comment]
API Assemblies should only contain code that you want mods to use. They should not include more than that. That code should probably be moved somewhere else.

**Comment by Noxalus** [comment]
That's the point of this issue, until now, I had another assembly to regroup all the code that uses the ModTool namespace to make sure I don't export it for the MOD project. And it was working because it's only UI element (the ones provided by your example) so it's simple prefab instantiate in the scene, no script from this assembly is used in the game core assembly.

But at some point, if I need to retrieve a prefab from a MOD to use it in the game core assembly, I will depends on the ModTool namespace right? Or did I miss something?

Could you give me an example where you instantiate a prefab from a MOD in a script (so using `Mod`'s `GetAsset` method?) and used in the core logic?

**Comment by Hello-Meow** [comment]
API assemblies shouldn't include all game code, but only shared scripts and interfaces. It should not have to reference ModTool.
