### ISSUE TITLE
Restriction Bug

### ISSUE THREAD

**Issue by HaHa6006** [Hello-Meow/ModTool#15]
Hello I Use ModTool. but users disable restrictions on Code Settings. How to disable?

**Comment by Hello-Meow** [comment]
You can change restrictions in a mod project, so the mod can be exported with no restrictions. However, in the game the restrictions will remain unchanged and the game will not load mods that violate any restrictions. 

I've considered making a disabled or blank custom editor for CodeSettings for the exporter, but if anyone wanted to edit the code settings they could do it anyways. Either through editor code or a text editor. I thought it was kind of pointless and left it as it was.

**Comment by HaHa6006** [comment]
Im set private on CodeSettings from source thanks. and its works!

Tim ***@***.***>, 19 Nis 2021 Pzt, 06:42 tarihinde şunu yazdı:
