### ISSUE TITLE
DLL's GUID changing when creating a new exporter

### ISSUE THREAD

**Issue by QuentinNev** [Hello-Meow/ModTool#18]
Hi !

We use Unity 2019.4.23f and to test the modding system of my game, I use the package created to import the new assembly in the modding project. I think it's easier for player to do it like this.
When creating a new exported to give to the player's new functionalities through the assembly it get sometimes a new GUID.

![image](https://user-images.githubusercontent.com/31761067/122772621-d9c6fc00-d2a7-11eb-8088-d0a73c1c21cc.png)

It only occurs once I restarted both the Unity Instance which created the export and the one which serves to create mod.
Every time I create a new exporter, this error is print in the editor's console :
![image](https://user-images.githubusercontent.com/31761067/122782063-b05e9e00-d2b0-11eb-8274-00e69c00deff.png)

It's really annoying because this breaks all references to scripts contained in this assembly.

![image](https://user-images.githubusercontent.com/31761067/122773178-67a2e700-d2a8-11eb-9f60-807ee2d1cbb3.png)

When we set them manually Unity doesn't recognize the script and all data are lost.

![image](https://user-images.githubusercontent.com/31761067/122773570-c23c4300-d2a8-11eb-9b18-cd4466289bb5.png)

Is there a way to prevent this to happen ? I'll continue to look for a possible fix or workaround and post it here if I find one.

Edit: I tried to uncheck ***Use GUIDs*** in .asmdef file's config but with no success as Unity can't seems to remember the change after it has been applied. (If you change inspected file and get back to asmdef the ***Use GUIDs*** is checked again...)

**Comment by Hello-Meow** [comment]
Thanks for the detailed issue report.

The issue was that Unity doesn't give persistent GUIDs to the copied API assemblies after restarts. After a restart, it would give API assemblies a different GUID, which would then cause the references to be broken.

The exporter creator should now give API assemblies a different GUID that should be the same between sessions. Please try the [new version](https://github.com/Hello-Meow/ModTool/blob/master/ModTool.unitypackage) and let me know if anything breaks.

**Comment by QuentinNev** [comment]
Thank you very much for this update ! I didn't expected to get a reply so quickly !

Unfortunately it didn't seem to work. 
I imported the new version of ModTool in the main project, created a new exporter and when importing it in the modding project it broke refs as expected. Then I restarted my computer, reopened the main project, created a new exporter (each time I do this I add a small change like adding or removing an unused variable) and imported it again on the modding project but it didn't recognized the GUID and references broke once more.

I found a workaround :
It requires to build the game. Like that Unity create the assembly and you can just drop it to replace the existing one in the modding template. Like this Unity seems to be completely blind to GUID and doesn't break everything.

It's a bit impacting on the workflow as we must wait ~15min each time we need to test some change in this assembly, but at least we're not using Unity 2018 (1+ hour of build time for a way smaller project) 

Do you think disabling this could solve the issue ?
![image](https://user-images.githubusercontent.com/31761067/122895567-8658ba80-d348-11eb-9735-b30d8a147241.png)

**Comment by QuentinNev** [comment]
Thank you very much for this update ! I didn't expected it so quickly !

The first time I tried it didn't seem to work, but I did a few more tries and it worked !
I still got the same warning in the import window, but now there's this one print on the console after import :
![image](https://user-images.githubusercontent.com/31761067/122907255-39c6ac80-d353-11eb-9449-f390466245ac.png)

But in the end everything scripts stay where they are and data in them are still there ! Great job !

I'm really excited to release this modding system, better implementation that in our previous game and the game itself was designed to be easily moddable. Can't wait to see what mod players will create ! :D

By the way, I want to say that I'm really admirative of your work ! ModTool is one of the best assets I worked with on the Asset Store, and it's free ! Thank you very much to offer us this amazing tool !

**Comment by Hello-Meow** [comment]
Good to see that it works. unfortunately Unity have added a lot of pointless and annoying warnings over the years. I'll have to find workarounds for those (if that's even possible).

**Comment by QuentinNev** [comment]
Just coming back to confirm that it's working perfectly !
Yup, for now I'll simply tell to modders to ignore them.
Thank you once again ! :)
