### ISSUE TITLE
Not Work On Unity 2018.2.5f1

### ISSUE THREAD

**Issue by youmu256** [Hello-Meow/ModTool#2]
Demo Script - Spinner Not Work
![error](https://user-images.githubusercontent.com/22392276/48685168-de0e7280-ebef-11e8-9306-b8fd127d5ad9.png)

**Comment by Hello-Meow** [comment]
Hi,

This is a known issue with Unity 2018. It no longer finds scripts in Assemblies that are loaded at runtime when loading asset bundles. This only happens in the editor. It should still work when you build the project.

**Comment by geigi** [comment]
Is there any way to fix this issue? Just tried with 2018.3 and it still happens. If I understand correctly you also can't edit any ScriptableObject (after closing and reopening Unity) whose class is defined in an Assembly? This would be a pretty serious issue...

**Comment by Hello-Meow** [comment]
This issue appears to be fixed in Unity 2019
