### ISSUE TITLE
ModBehaviour issue

### ISSUE THREAD

**Issue by T38a** [Hello-Meow/ModTool#21]
The type or namespace name 'ModBehaviour' could not be found (are you missing a using directive or an assembly reference?)	
public class test2 : ModBehaviour
It says something wrong with the mod behaviour thing

**Comment by TheKing349** [comment]
Did you ever end up figuring this out? I'm having the same issue

**Comment by Hello-Meow** [comment]
ModBehaviour is no longer a thing. Where did you come across ModBehaviour?

**Comment by TheKing349** [comment]
The YouTube example on your Unity Asset page still shows you to change to ModBehaviour. I know the YouTube example is not a tutorial, I was just trying to figure out how it all worked

> ModBehaviour is no longer a thing. Where did you come across ModBehaviour?

The YouTube example on your Unity Asset Store Page shows you changing : MonoBehaviour to : ModBehaviour. I know the YouTube example is not a tutorial but just trying to figure out how it works

**Comment by Hello-Meow** [comment]
Yeah that video is quite dated. ModBehaviour was once used to track a mod's objects, but now that's done differently.

**Comment by TheKing349** [comment]
Ah makes sense
