### ISSUE TITLE
Mods not found and loading after switching to another scene

### ISSUE THREAD

**Issue by Maxus376** [Hello-Meow/ModTool#28]
Hello, i'm using Unity 2018.4.36f1. ModTool version: 2.0. In previous version out Asset Store my solution for autoloading mods in game is working. But it doesn't work in this version.

The problem is that I use the mod menu from the plugin in the game menu itself, when I click "Play", then after loading the world, mods are loaded (I created a script, wrote an appeal to the mod menu, which I copied from the game menu into the game world, hiding the visual elements, and this is the command: mod.Load(); (mod is a menu mod)). It used to work for sure, when I updated the plugin version, it stopped working. I turned off my script, took the code from the mod menu script, but the mods are no longer visible after loading the world. Mods will be visible and loaded when I turn on the game directly from the game world scene.

![image](https://github.com/user-attachments/assets/65d2bb77-badf-4a28-bc16-804ee79c2538)
As you can see, mods are visible in the game menu
![image](https://github.com/user-attachments/assets/29bc69b2-e8ce-4f29-8b35-2545e4be59c4)
But after loading the world from the menu, the mods are not visible
![image](https://github.com/user-attachments/assets/427784ba-b4a2-4bdc-8f7a-0a08fc948133)
Enabling the game directly from the game world scene, mods are visible

**Comment by Maxus376** [comment]
I have found a solution! Thanks to the discussions in this repository. In one topic I found how a person tries to upload mods after deletion, or something like that, I saw the code and decided to redo it for myself, and it really worked!

```
ModManager.Refresh();
foreach (var mod in ModManager.mods)
{
	foreach (var scene in mod.scenes)
	{
		scene.Load();
	}
	if(mod.isEnabled) mod.Load();
}
```

**Comment by Hello-Meow** [comment]
What could have caused this is that in previous versions, auto refreshing worked a little differently. In the most recent version, the example ModMenu does the auto refreshing itself. In previous versions, it was done in ModManager.
