### ISSUE TITLE
Errors when exporting mod

### ISSUE THREAD

**Issue by pipe01** [Hello-Meow/ModTool#3]
I get the following errors when trying to export a mod for my game on Unity 2018.3.1f1

![imagen](https://user-images.githubusercontent.com/3885705/51395547-61d7d300-1b3d-11e9-8ff9-7c7b4cce0d0c.png)

**Comment by Hello-Meow** [comment]
Thanks for reporting this issue. It looks like it's trying to export and backup packages, which does not seem like a good idea. I'll take a look.

**Comment by pipe01** [comment]
Awesome, thank you

**Comment by Hello-Meow** [comment]
The packages folder should now be ignored when exporting mods.

**Comment by pipe01** [comment]
Thanks a ton!
