### ISSUE TITLE
Custom data in ModInfo

### ISSUE THREAD

**Issue by pipe01** [Hello-Meow/ModTool#4]
It would be great if you could extend the `ModInfo` class with additional info your mod may need. This could be accomplished through a `Dictionary<string, object> ModInfo.Extra`.

**Comment by Hello-Meow** [comment]
Currently ModInfo is serialized with JsonUtility, which does not support Dictionary.

This sounds like a good feature to have, but I'm not sure how the info would have to be communicated between the game project and the mod project. How would the modder configure the extra info or how would the exporter show this as an option?

**Comment by pipe01** [comment]
Maybe you would create a json file as an asset in theod project, filling a class that you'd specify in the exporter.
