### ISSUE TITLE
Synchronous mod finding

### ISSUE THREAD

**Issue by pipe01** [Hello-Meow/ModTool#6]
I'd like to only load mods once at startup and never after that.

**Comment by QuentinNev** [comment]
I may be a little late, but using the provided example :

```c#
private void Load()
    {
        //load mods
        foreach (Mod mod in modItems.Keys)
        {
            if(mod.isEnabled)
                mod.LoadAsync();
        }

        SetTogglesInteractable(false);

        loadButton.GetComponentInChildren<Text>().text = "U N L O A D";

        isLoaded = true;
    }
```

Replacing `if(mod.isEnabled) mod.LoadAsync();` with `if(mod.isEnabled) mod.Load();` should do what you want.
And only call this once at startup of course.

**Comment by pipe01** [comment]
The problem is that the mod discovery is still done in the background. I made a [fork](https://github.com/pipe01/ModTool) in order to solve this until a proper solution is implemented.

**Comment by Hello-Meow** [comment]
I'm sorry for the late reply.

You should be able to disable mod discovery by setting ModManager.refreshInterval to 0.
