### ISSUE TITLE
Fails to import on Unity 2019.1

### ISSUE THREAD

**Issue by cpetry** [Hello-Meow/ModTool#7]
I'm trying to import this into a project developed in Unity 2019.1 with .Net 4.x.
I get several different errors trying to get this to work.

One for example is:
```
Unloading broken assembly Assets/ModTool/ModTool.Shared.dll, this assembly can cause crashes in the runtime
0x00007FF7D82E818C (Unity) StackWalker::GetCurrentCallstack
0x00007FF7D82EB641 (Unity) StackWalker::ShowCallstack
0x00007FF7D6A4AFF5 (Unity) GetStacktrace
0x00007FF7D8D0DE20 (Unity) DebugStringToFile
0x00007FF7D82436D0 (Unity) MonoManager::SetupLoadedEditorAssemblies
0x00007FF7D8235208 (Unity) MonoManager::EndReloadAssembly
0x00007FF7D82406E2 (Unity) MonoManager::ReloadAssembly
0x00007FF7D652C6B6 (Unity) ReloadAllUsedAssemblies
0x00007FF7D6526926 (Unity) HandleCompileStatus
0x00007FF7D652236A (Unity) CompileScriptsWait
0x00007FF7D6521BCA (Unity) CompileDirtyScriptsForEditorSyncInternal
0x00007FF7D6521A4B (Unity) CompileDirtyScriptsForEditorSync
0x00007FF7D6522001 (Unity) CompileScriptsForEditorSync
0x00007FF7D652A351 (Unity) LoadMonoAssembliesAndRecompileIfNecessary
0x00007FF7D6A89B38 (Unity) Application::InitializeProject
0x00007FF7D6D5DAFA (Unity) WinMain
0x00007FF7D96A653E (Unity) __scrt_common_main_seh
0x00007FFDB9EC7974 (KERNEL32) BaseThreadInitThunk
0x00007FFDBC95A271 (ntdll) RtlUserThreadStart
```

I tried recompiling the libraries for .Net 4.7 but that didn't help.

EDIT:
By the way, I am using [Zenject](https://github.com/modesttree/Zenject/) which also seems to somewhat rely on Mono.Cecil. 
At first I got:
`PrecompiledAssemblyException: Multiple precompiled assemblies with the same name Mono.Cecil.dll included for the current platform. Only one assembly with the same name is allowed per platform. Assembly path: {0}`
which I 'supressed' by deleting the Mono.Cecil in this package and using the Unity PackageManager to fetch the latest Mono.Cecil from nuget.
But that also doesn't help. I can't get ModTool to run.

**Comment by cpetry** [comment]
I also noticed that importing this package resulted in a crash on CodeSettings.asset
```
A default asset was created for 'Assets/ModTool/Resources/CodeSettings.asset' because the asset importer crashed on it last time.
You can select the asset and use the 'Assets -> Reimport' menu command to try importing it again, or you can replace the asset and it will auto import again.
```

**Comment by Hello-Meow** [comment]
ModTool uses an older version of Mono.Cecil, which is probably what's causing this. I haven't had the time yet to upgrade.
